Repository zuul-hcl-org/gameoflife, pull requests merged in 2019-06, with the labels that each got.

#1 Create Test.txt
  Test.txt
Labels: emea, failed, nafta

#8 Create test3.txt
  test3.txt
Labels: failed, nafta, ready-for-merge

#9 Create hello
  hello
Labels: failed, nafta, ready-for-merge

#16 Create variable_test
  variable_test
Labels: emea, nafta

#37 emea
  test.txt
Labels: merge-not-ready

#38 emea test
  .zuul.yaml
Labels: merge-not-ready

#46 Create new test
  new test
Labels: emea, failed, merged, nafta, ready-for-merge

#48 Create gatetest
  gatetest
Labels: merged, nafta, ready-for-merge

#56 Dev
  nodtestest
  test.txt
Labels: emea

#73 Create new_request
  new_request
Labels: nafta, ready-for-merge
